---
  - name: cp joomla
    become: yes
    become_method: sudo
    shell: "cp -r /tmp/joomla /var/www"

  - name: copy info.php
    become: yes
    become_method: sudo
    copy: src=files/info.php dest=/var/www/joomla

  - name: passwd mysql
    copy: src=files/script.sql dest=/tmp/

  - name: mysql script
    become: yes
    become_method: sudo
    shell: "mysql </tmp/script.sql"

  - name: phpadmin script
    become: yes
    become_method: sudo
    copy: src=files/phpadmin.sh dest=/tmp/

  - name: restart apache2
    become: yes
    become_method: sudo
    shell: "systemctl restart apache2"

  - name: php script
    become: yes
    become_method: sudo
    shell: "sh /tmp/phpadmin.sh"

  - name: install phpmyadmin
    become: yes
    become_method: sudo    
    apt: name=phpmyadmin state=latest

  - name: configuration.php
    become: yes
    become_method: sudo
    copy: src=files/configuration.php dest=/var/www/joomla
