---
incluir_task0: true
incluir_task1: true
incluir_task2: true
incluir_task3: true
incluir_task4: true
incluir_task5: true
incluir_task6: true
incluir_task7: true 
incluir_task8: true
incluir_task9: true
incluir_task10: true
# defaults file for joomla